### ISSUE TITLE
NVIDIA proprietary driver will not install/build with 5.4.1-xanmod

### ISSUE THREAD

**Issue by Brainiarc7** [xanmod/linux#30]
Hello there,

The latest NVIDIA proprietary driver, R440.33, will not build its' DKMS modules in the aforementioned kernel version:

`tail -n 50 /var/lib/dkms/nvidia/440.33.01/build/make.log | xclip -sel clip`

```sh
In file included from <command-line>:0:0:
././include/linux/compiler_types.h:210:24: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
 #define asm_inline asm __inline
                        ^
./arch/x86/include/asm/bug.h:35:2: note: in expansion of macro ‘asm_inline’
  asm_inline volatile("1:\t" ins "\n"    \
  ^~~~~~~~~~
./arch/x86/include/asm/bug.h:79:2: note: in expansion of macro ‘_BUG_FLAGS’
  _BUG_FLAGS(ASM_UD2, BUGFLAG_WARNING|(flags));  \
  ^~~~~~~~~~
./include/asm-generic/bug.h:90:19: note: in expansion of macro ‘__WARN_FLAGS’
 #define __WARN()  __WARN_FLAGS(BUGFLAG_TAINT(TAINT_WARN))
                   ^~~~~~~~~~~~
./include/asm-generic/bug.h:115:3: note: in expansion of macro ‘__WARN’
   __WARN();      \
   ^~~~~~
/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv.c:4378:5: note: in expansion of macro ‘WARN_ON’
     WARN_ON(rm_set_external_kernel_client_count(sp, NV_STATE_PTR(nvl), NV_FALSE) != NV_OK);
     ^~~~~~~
/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-acpi.c: In function ‘nv_acpi_methods_init’:
/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-acpi.c:618:5: error: implicit declaration of function ‘NV_ACPI_WALK_NAMESPACE’; did you mean ‘ACPI_NAMESPACE’? [-Werror=implicit-function-declaration]
     NV_ACPI_WALK_NAMESPACE(ACPI_TYPE_DEVICE, ACPI_ROOT_OBJECT,
     ^~~~~~~~~~~~~~~~~~~~~~
     ACPI_NAMESPACE
/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-vm.c: In function ‘nv_set_memory_array_type’:
/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-vm.c:66:13: error: implicit declaration of function ‘set_memory_array_uc’; did you mean ‘set_pages_array_uc’? [-Werror=implicit-function-declaration]
             set_memory_array_uc(pages, num_pages);
             ^~~~~~~~~~~~~~~~~~~
             set_pages_array_uc
cc1: some warnings being treated as errors
scripts/Makefile.build:265: recipe for target '/var/lib/dkms/nvidia/440.33.01/build/nvidia/os-interface.o' failed
make[2]: *** [/var/lib/dkms/nvidia/440.33.01/build/nvidia/os-interface.o] Error 1
cc1: some warnings being treated as errors
cc1: some warnings being treated as errors
scripts/Makefile.build:265: recipe for target '/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-acpi.o' failed
make[2]: *** [/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-acpi.o] Error 1
scripts/Makefile.build:265: recipe for target '/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv.o' failed
make[2]: *** [/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv.o] Error 1
/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-vm.c:69:13: error: implicit declaration of function ‘set_memory_array_wb’; did you mean ‘set_pages_array_wb’? [-Werror=implicit-function-declaration]
             set_memory_array_wb(pages, num_pages);
             ^~~~~~~~~~~~~~~~~~~
             set_pages_array_wb
cc1: some warnings being treated as errors
scripts/Makefile.build:265: recipe for target '/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-vm.o' failed
make[2]: *** [/var/lib/dkms/nvidia/440.33.01/build/nvidia/nv-vm.o] Error 1
Makefile:1652: recipe for target '/var/lib/dkms/nvidia/440.33.01/build' failed
make[1]: *** [/var/lib/dkms/nvidia/440.33.01/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.0-xanmod0'
Makefile:81: recipe for target 'modules' failed
make: *** [modules] Error 2

```

**Comment by xanmod** [comment]
https://forum.xanmod.org/thread-3635-post-6661.html#pid6661
