### ISSUE TITLE
Include Aspeed GPU Drivers.

### ISSUE THREAD

**Issue by ne0ark** [xanmod/linux#31]
I am running into issue when trying to install GPU Drivers:

Can you please include them: https://www.aspeedtech.com/support.php

```
dpkg -i ast-drm-linux5.00.deb
(Reading database ... 126091 files and directories currently installed.)
Preparing to unpack ast-drm-linux5.00.deb ...

------------------------------
Deleting module version: 1.10.3
completely from the DKMS tree.
------------------------------
Done.
Unpacking ast-dkms (1.10.3) over (1.10.3) ...
Setting up ast-dkms (1.10.3) ...
Loading new ast-1.10.3 DKMS files...
Building for 5.4.2-xanmod2
Building for architecture x86_64
Building initial module for 5.4.2-xanmod2
ERROR (dkms apport): kernel package linux-headers-5.4.2-xanmod2 is not supported
Error! Bad return status for module build on kernel: 5.4.2-xanmod2 (x86_64)
Consult /var/lib/dkms/ast/1.10.3/build/make.log for more information.
```
```
cat /var/lib/dkms/ast/1.10.3/build/make.log
DKMS make.log for ast-1.10.3 for kernel 5.4.2-xanmod2 (x86_64)
Sun Dec 15 15:55:07 UTC 2019
make: Entering directory '/var/lib/dkms/ast/1.10.3/build/src'
make -C /lib/modules/5.4.2-xanmod2/build M=/var/lib/dkms/ast/1.10.3/build/src modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.2-xanmod2'
  CC [M]  /var/lib/dkms/ast/1.10.3/build/src/ast_drv.o
/var/lib/dkms/ast/1.10.3/build/src/ast_drv.c: In function ‘ast_drm_freeze’:
/var/lib/dkms/ast/1.10.3/build/src/ast_drv.c:102:2: error: implicit declaration of function ‘drm_kms_helper_poll_disable’; did you mean ‘drm_fb_helper_pan_display’? [-Werror=implicit-function-declaration]
  drm_kms_helper_poll_disable(dev);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
  drm_fb_helper_pan_display
/var/lib/dkms/ast/1.10.3/build/src/ast_drv.c: In function ‘ast_drm_resume’:
/var/lib/dkms/ast/1.10.3/build/src/ast_drv.c:138:2: error: implicit declaration of function ‘drm_kms_helper_poll_enable’; did you mean ‘drm_fb_helper_fill_info’? [-Werror=implicit-function-declaration]
  drm_kms_helper_poll_enable(dev);
  ^~~~~~~~~~~~~~~~~~~~~~~~~~
  drm_fb_helper_fill_info
cc1: some warnings being treated as errors
scripts/Makefile.build:265: recipe for target '/var/lib/dkms/ast/1.10.3/build/src/ast_drv.o' failed
make[2]: *** [/var/lib/dkms/ast/1.10.3/build/src/ast_drv.o] Error 1
Makefile:1654: recipe for target '/var/lib/dkms/ast/1.10.3/build/src' failed
make[1]: *** [/var/lib/dkms/ast/1.10.3/build/src] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.2-xanmod2'
Makefile:18: recipe for target 'modules' failed
make: *** [modules] Error 2
make: Leaving directory '/var/lib/dkms/ast/1.10.3/build/src'
```

**Comment by xanmod** [comment]
This dkms script is not compatible with linux 5.4.

Aspeed video module is already built-in in kernel. 
Don't need to rebuild by dkms.
> CONFIG_VIDEO_ASPEED=m
> `modinfo aspeed-video`

Try: `sudo modprobe aspeed-video`

To load at boot time:
https://unix.stackexchange.com/questions/71064/systemd-automate-modprobe-command-at-boot-time

**Comment by ne0ark** [comment]
Odd I get the following error:

May be wrong drivers?

```
Setting up linux-headers-5.4.4-xanmod3 (1.191218) ...
Setting up linux-image-5.4.4-xanmod3 (1.191218) ...
 * dkms: running auto installation service for kernel 5.4.4-xanmod3                                                                                                                                                                                      [ OK ] 
update-initramfs: Generating /boot/initrd.img-5.4.4-xanmod3
cryptsetup: WARNING: failed to detect canonical device of /dev/md3
cryptsetup: WARNING: could not determine root device from /etc/fstab
W: Possible missing firmware /lib/firmware/ast_dp501_fw.bin for module ast
I: The initramfs will attempt to resume from /dev/sdc4
I: (UUID=fbcc82f2-e09a-4876-97dd-746536beecec)
I: Set the RESUME variable to override this.
```

**Comment by xanmod** [comment]
Extract the [ast_dp501_fw.bin.gz](https://github.com/xanmod/linux/files/3981782/ast_dp501_fw.bin.gz) firmware file in to /lib/firmware as root:

`gzip -dk ast_dp501_fw.bin.gz && sudo mv ast_dp501_fw.bin /lib/firmware/`
