### ISSUE TITLE
amd-pstate.c does not compile with clang and llvm in kernels 5.14.18, 5.15.2, 5.15.2-tt

### ISSUE THREAD

**Issue by bugcrazy** [xanmod/linux#218]
drivers/opp/cpu.o
  CC      drivers/opp/debugfs.o
  AR      drivers/opp/built-in.a
  CC      drivers/cpufreq/cpufreq.o
  CC      drivers/cpufreq/freq_table.o
  CC      drivers/cpufreq/cpufreq_stats.o
  CC      drivers/cpufreq/cpufreq_performance.o
  CC      drivers/cpufreq/cpufreq_powersave.o
  CC      drivers/cpufreq/cpufreq_userspace.o
  CC      drivers/cpufreq/cpufreq_ondemand.o
  CC      drivers/cpufreq/cpufreq_conservative.o
  CC      drivers/cpufreq/cpufreq_governor.o
  CC      drivers/cpufreq/cpufreq_governor_attr_set.o
  CC      drivers/cpufreq/acpi-cpufreq.o
  CC      drivers/cpufreq/amd-pstate.o
drivers/cpufreq/amd-pstate.c:257:6: error: variable 'amd_des_perf' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
        if (target_perf < capacity)
            ^~~~~~~~~~~~~~~~~~~~~~
drivers/cpufreq/amd-pstate.c:272:40: note: uninitialized use occurs here
        amd_des_perf = clamp_t(unsigned long, amd_des_perf,
                                              ^~~~~~~~~~~~
./include/linux/minmax.h:124:60: note: expanded from macro 'clamp_t'
#define clamp_t(type, val, lo, hi) min_t(type, max_t(type, val, lo), hi)
                                                           ^~~
./include/linux/minmax.h:112:48: note: expanded from macro 'max_t'
#define max_t(type, x, y)       __careful_cmp((type)(x), (type)(y), >)
                                                     ^
./include/linux/minmax.h:38:14: note: expanded from macro '__careful_cmp'
                __cmp_once(x, y, __UNIQUE_ID(__x), __UNIQUE_ID(__y), op))
                           ^
note: (skipping 1 expansions in backtrace; use -fmacro-backtrace-limit=0 to see all)
./include/linux/minmax.h:104:48: note: expanded from macro 'min_t'
#define min_t(type, x, y)       __careful_cmp((type)(x), (type)(y), <)
                                                     ^
./include/linux/minmax.h:38:14: note: expanded from macro '__careful_cmp'
                __cmp_once(x, y, __UNIQUE_ID(__x), __UNIQUE_ID(__y), op))
                           ^
./include/linux/minmax.h:31:25: note: expanded from macro '__cmp_once'
                typeof(x) unique_x = (x);               \
                                      ^
drivers/cpufreq/amd-pstate.c:257:2: note: remove the 'if' if its condition is always true
        if (target_perf < capacity)
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~
drivers/cpufreq/amd-pstate.c:249:56: note: initialize the variable 'amd_des_perf' to silence this warning
        unsigned long amd_max_perf, amd_min_perf, amd_des_perf,
                                                              ^
                                                               = 0
1 error generated.
make[2]: *** [scripts/Makefile.build:277: drivers/cpufreq/amd-pstate.o] Error 1
make[1]: *** [scripts/Makefile.build:540: drivers/cpufreq] Error 2
make: *** [Makefile:1869: drivers] Error 2

**Comment by xanmod** [comment]
Try the make defined like this:
`make LLVM=1 LLVM_IAS=1`

https://www.kernel.org/doc/html/latest/kbuild/llvm.html

**Comment by bugcrazy** [comment]
> Try the make defined like this: `make LLVM=1 LLVM_IAS=1`
> 
> https://www.kernel.org/doc/html/latest/kbuild/llvm.html

I have already tried this parameter and the individual parameters, the result is the same, I had already tested before, the parameters of the site.

I compile Xanmod kernel for Void Linux, I have been ported for Void: https://notabug.org/Marcoapc/voidxanmodK

**Comment by xanmod** [comment]
Updated to v5: https://lore.kernel.org/all/20211130123641.1449041-1-ray.huang@amd.com/

**Comment by bugcrazy** [comment]
I compiled all current versions of the Xanmod kernel, the problem has been fixed!

The problem, that the code was not mature, now they added support for clang and llvm.
